apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: 686255959744.dkr.ecr.us-east-1.amazonaws.com/vote:latest
        name: vote
        ports:
        - containerPort: 80
          name: vote
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0.25
        resources:
          requests:
            cpu: 0.1
